config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :books
  resources :book_requests
  resources :users
  
  get 'locatebooks', to:      'locatebooks#locatebooks'
  get '/users', to: 'users#index'
  get '/profile', to: 'users#profile'

  get 'around/:lat,:lng', to: 'books#by_location', :constraints => {:lat => /\-?\d+(.\d+)?/, :lng => /\-?\d+(.\d+)?/ }  
  get 'get_around/:lat,:lng/:range', to: 'books#books_around', :constraints => {:lat => /\-?\d+(.\d+)?/, :lng => /\-?\d+(.\d+)?/ , :range => /\d+/ }
  post 'book_transactions/request', to: 'book_transactions#request_book'
  post 'book_transactions/return', to: 'book_transactions#return_book'
  post 'book_transactions/approve', to: 'book_transactions#approve_book_request'
  post 'book_transactions/reject', to: 'book_transactions#reject_book_request'
  post '/rate' => 'rater#create', :as => 'rate'
  match "/books/add_new_comment" => "books#add_new_comment", :as => "add_new_comment_on_book", :via => [:post]
  get '/book_transactions', to: 'book_transactions#index'

  root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	include ActiveModel::Serializers::JSON

	mount_uploader :image_url, ImageUrlUploader # Tells rails to use this uploader for this model.
	belongs_to :owner, :class_name => 'User'
	has_and_belongs_to_many :genres
	has_many :book_transactions
	has_many :borrowers, :through => :book_transactions


	# There are long book names so using a max of 100 chars 
	# Eg: Proceedings of the Second International Workshop on Nude Mice 
	
	validates  :title, presence: true, length: { maximum: 100 }
	validates  :author, presence: true, length: { maximum: 30}
	ratyrate_rateable 'author'
	acts_as_commentable

	scope :latest_books, lambda { order(":created_at ASC")}
	scope :search, lambda{ |args|
		where('title LIKE :query OR author LIKE :query', query:"%#{args}%")
	}

	def is_borrowed
		if self.book_transactions.where("borrowed AND returned",true,false).first
			return true
		else
			return false
		end
	end

	def is_with
		trans = self.book_transactions.where("borrowed=? AND returned=?",true,false).first
		if trans
			return trans.borrower
		else
			return self.owner
		end
	end
end

app/models/concerns/book.rb
class Book < ActiveRecord::Base
	include ActiveModel::Serializers::JSON

	belongs_to :user

	# There are long book names so using a max of 100 chars 
	# Eg: Proceedings of the Second International Workshop on Nude Mice 
	
	validates  :Title, presence: true, length: { maximum: 100 }
	validates  :Author, presence: true, length: { maximum: 30}

end

app/controllers/books_controller.rb
#controller for handling all the views for books
require 'set'
require 'base64'
require 'json'
require 'will_paginate/array'

class BooksController < ApplicationController
  before_action :authenticate_user!, :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    books_to_consider=user_signed_in? ? (Book.where.not(owner_id: current_user.id) if stale?(Book.where.not(owner_id: current_user.id))) : (Book.all if stale?(Book.where.not(owner_id: current_user.id)))
    @books=[]
    books_to_consider.each do |book|
      unless BookTransaction.where("book_id=? AND (approved=false OR requested=false OR returned=false)",book.id).exists?
        @books.push(book)
      end
    end
    @books = @books.where(genre: params[:genre]) if params[:genre].present?
    @books = @books.where(author: params[:author]) if params[:author].present?
    @books = @books.where(title: params[:title]) if params[:title].present?
    
    if params[:userid].present?
      books_by_user=[]
      @books.each do |book|
        if book.owner_id=params[:userid]
          books_by_user.push(book)
        end
      end
      @books=books_by_user
    end

    @books = @books.search(params[:search]) if params[:search].present?
    @books = @books.paginate(:page => params[:page], :per_page => 15)
    @unique_authors = Book.uniq.pluck(:author)
    @unique_genre = Book.uniq.pluck(:genre)
    #render :layout => false
    
  end

  def add_new_comment
    book = Book.find(params[:id])
    comment = Comment.new 
    comment.user_id = current_user.id
    comment.comment = params[:comment]
    comment.commentable_id = book.id
    comment.save!
    redirect_to :action => :show, :id => book
  end
 

  # GET /books/1
  # GET /books/1.json
  def show
    @user = current_user
    book_owner = User.where(id: @book.owner_id)
    book_owner = book_owner[0]
    @book_owner_lat = book_owner["lat"]
    @book_owner_lng = book_owner["lng"]
    @book_owner_add = book_owner["address"]
    #@comments = Comment.order('created_at DESC').where(commentable_id: @book.id)
    @comments = Comment.unscoped { Comment.order("created_at DESC").where(commentable_id: @book.id).limit(20) }
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    if current_user
     @user=current_user
     unless params[:genre].nil?
      params[:genre]=params[:genre].downcase
    end
     @book = Book.new(book_params)
     @book.owner_id=@user.id
   else
     redirect_to new_user_session_path, notice: 'You are not logged in.'
    end
    

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


   def books_around
    latlng = [ params[:lat], params[:lng] ]
    users = User.within( params[:range], :origin => latlng)
    books = Book.where(owner_id: users)
    modi_books = {}
    array = []
    for user in users
	modi_books = {}
	modi_books["title"] = ''
       for book in books
           #modi_books[
	   if user["id"] == book["owner_id"]
		modi_books["username"] = user["username"]
		modi_books["owner_id"] = book["owner_id"]
		modi_books["id"] = book["id"]
		if modi_books["title"] == ''
			modi_books["title"] += book["title"]
		else
			modi_books["title"] += ", "+book["title"]
		end
		modi_books["lat"] = user["lat"]
		modi_books["lng"] = user["lng"]
	   end
       end
	array.push(modi_books)
    end
    render json: { books:array}
    end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :edition, :genre, :ratings, :image_url, :publisher, :ISBN)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class="container">
  <div class="col-sm-4 col-sm-offset-1">
    <div class="login-form"><!--login form-->
      <h2>Lend a Book</h2>
      <%= form_for(@book) do |f| %>
        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.text_field :title, :placeholder => "Book Title" %>
        <%= f.text_field :author, :placeholder => "Author" %>

        <%= f.text_field :genre, :placeholder => "Genre" %>
        <%= f.text_field :publisher, :placeholder => "Publisher" %>
        <%= f.text_field :ISBN, :placeholder => "ISBN" %>
        <%= f.file_field :image_url, :placeholder => "Photo", :class => "btn-file"%>
        <button type="submit" class="btn btn-default">Lend</button>
      <% end %>
    </div>
  </div>
</div>

app/views/books/borrow_success.html.erb
<div id="show_book_request">
  <h2><%= @message_to_view %></h2>
  <br/>
  <br/>
  <div class="col-sm-4"></div>
  <div class="col-sm-4">
    <div class="product-image-wrapper">
      <div class="single-products">
        <div class="productinfo text-center">
          <% if (@book.image_url == nil) %>
            <img scr = "assets/images/placeholder_cover.jpg" >
          <% else %>
            <%= image_tag @book.image_url, {height: 300}%>
          <% end %>
          <h2><%= @book.title %></h2>
          <p><%= @book.author %></p>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-4"></div>
</div>

app/views/books/create.html.erb
<div class='col-md-offset-3 col-md-6 pad-down'>
 <form action="/save_book_data" method="post" enctype="multipart/form-data">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
  <div class='form-group'>
    <label>Image: </label>
    <input class="form-control" type="file" id="image" name="image">
  </div>
  <div class='form-group'>
    <label>Title: </label>
    <input class="form-control" type="text" id="title" name="title" placeholder="eg. The Hero's Journey">
  </div>
  <div class='form-group'>
    <label>Author: </label>
    <input class="form-control" type="text" id="author" name="author" placeholder="eg. Campbell">
  </div>
  <div class='form-group'>
    <label>Blurb: </label>
    <textarea class="form-control" name="blurb" rows="5"></textarea>
  </div>
  <div class='form-group'>
    <label>ISBN: </label>
    <input class="form-control" type="text" id="isbn" name="isbn">
  </div>
  <input class="btn btn-success" id="save-book" type="submit" value="Save">
 </form>
</div>

app/views/books/edit.html.erb
<%= render 'form' %>
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div id="container">
  
    <div class="features_items"><!--features_items-->
      <h2 class="title text-center">Listed Books</h2>
      <% @books.each do |book| %>
        <div class="col-sm-4">
          <div class="product-image-wrapper">
            <div class="single-products placeholder-image">
              <div class="productinfo text-center">
                <% if (book.image_url == nil) %>
                  <%= image_tag "placeholder_cover.jpg", {height: 200}%>
                <% else %>
                  <%= image_tag book.image_url, {height: 200}%>
                <% end %>
                <h2><%= link_to book.title, book %></h2>
                <p><%= book.author %></p>
              </div>
              <div class="product-overlay">
                <div class="overlay-content">
                  <h2 style="padding_bottom:80px;"><%= link_to book.title, book %></h2>
                  <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-comments"></i>Message the Lender</a><br>
                  <button type="button" class="btn btn-fefault cart" data-toggle="modal" data-target="#borrow_Modal"><i class=\"fa fa-shopping-cart\"></i>Borrow</button>
                </div>
              </div>

              <div id="borrow_Modal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <form class="contact" name="book_request" action="book_transactions/request" enctype="multipart/form-data" method="post">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Borrow <%= book.title %></h4>
                    </div>
                    <div class="modal-body">
                      
                        <input type="hidden" name="book_id" value="<%= book.id %>">
                        <label class="label" for="loan_period">I want to borrow it for: </label>
                        <input type="number" name="loan_period" class="input-xlarge"><br>
                      
                    </div>
                    <div class="modal-footer">
                      <button class="btn btn-success" type="submit" value="Request Book">Request Book</button>
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                  </form>

                </div>
              </div>

            </div>
            <div class="choose">
              <ul class="nav nav-pills nav-justified">
                <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <!--features_items-->
    <%= will_paginate @books , renderer: BootstrapPagination::Rails%>
</div>

app/views/books/new.html.erb
<%= render 'form' %>

app/views/books/show.html.erb
<section>
  <div class="container">
    <div class="row">
    <div class="product-details"><!--product-details-->
      <div class="col-sm-8 padding-right">
        <div class="col-sm-6">
          <div class="view-product">
            <img class="book-image" src="<% unless @book.image_url.nil? %><%= @book.image_url %><% else %>placeholder_cover.jpg<% end %>" />
          </div>
        </div>
        <div class="col-sm-6">
          <div class="product-information"style="height:600px"><!--/product-information-->
            <h2><%= @book.title %></h2>
            <p>Book ID: <%= @book.id %></p>
            <p><b>Author:</b> <%= @book.author %></p>
            <p><b>Publisher:</b> <%= @book.publisher %></p>
            <p><b>Edition:</b> <%= @book.edition %></p>
            <p><b>ISBN:</b> <%= @book.ISBN%></p>
            <p><b>Genre:</b> <%= @book.genre%></p>
            <% if not(@user.id==@book.owner_id) %>
              <button type="button" class="btn btn-fefault cart" data-toggle="modal" data-target="#borrow_Modal" style="margin-left:0px"><i class="fa fa-shopping-cart"></i>Borrow</button>
            <% end %>
            <!-- Modal -->
              <div id="borrow_Modal" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <form class="contact" name="book_request" action="/book_transactions/request" enctype="multipart/form-data" method="post">
                  <!-- Modal content-->
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                      <h4 class="modal-title">Borrow <%= @book.title %></h4>
                    </div>
                    <div class="modal-body">
                      
                        <input type="hidden" name="book_id" value="<%= @book.id %>">
                        <label class="label" for="loan_period">I want to borrow it for: </label>
                        <input type="number" name="loan_period" class="input-xlarge"><br>
                      
                    </div>
                    <div class="modal-footer">
                      <button class="btn btn-success" type="submit" value="Request Book">Request Book</button>
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                  </form>

                </div>
              </div>
            <p><b>Rating:</b><%= rating_for @book,  "author",star_path: '../' %></p>
            <%= form_tag "/books/add_new_comment" do %>
              <%= hidden_field_tag "id", @book.id %>
              <%= text_area_tag "comment", nil, :placeholder => "Add your comment here" %>
              <%= submit_tag "Comment",class: "btn btn-fefault cart" %>
            <% end %>
    <br/>
    
          </div>
          <!--/product-information-->
        </div>
      </div>
      <div class="col-sm-4 pad-down" >
        <div class="map minimap" style= 'width:900px; height:600px'></div>
        <script>
          var current_user_lat_lng = {lat: <%= @book_owner_lat %>, lng: <%= @book_owner_lng %>}; var curent_user_address = "<%= @book_owner_add%>";
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=drawing&callback=book_initmap"></script>
      </div>
    </div>
    <!--product-details-->
  
  <!--row-->
  <div class="row">
    <legend>Comments</legend>
    <% @comments.each do |comment| %>
      <div class="row">
        <div class="col-md-12">
          <div class="blog-post-area">
            <div class="single-blog-post">
              <div class="post-meta">
                <ul>
                  <li><i class="fa fa-user"></i><!-- <a href="/users/"+<%=comment.user_id%>> --><%= link_to comment.user.username, comment.user %></a></li>
                <li><i class="fa fa-calendar"></i>  <%= comment.created_at%></li>
              </ul>
            </div>
            <p class="comment-text"><%= comment.comment %></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<!--container-->
</section>

app/views/books/unique_index.html.erb
<%= stylesheet_link_tag "main.css" %>
<%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css' %> 


<div class="col-sm-12 padding-right">
<div class="features_items"><!--features_items-->
  <h2 class="title text-center">Listed Books</h2>
  <% @books.each do |book| %>
    <div class="col-sm-4">
      <div class="product-image-wrapper">
        <div class="single-products placeholder-image">
          <div class="productinfo text-center">
            <% if (book.image_url == nil) %>
              <%= image_tag "placeholder_cover.jpg", {height: 250}%>
            <% else %>
              <%= image_tag book.image_url, {height: 250}%>
            <% end %>
            <h2><%= link_to book.title, book %></h2>
            <p><%= book.author %></p>
          </div>
          <div class="product-overlay">
            <div class="overlay-content">
              <h2 style="padding-bottom:80px; color : #ffffff"><%= link_to book.title, book %></h2>
              <a href="#" class="btn btn-default add-to-cart"><i class="fa fa-comments"></i>Message</a><br>
              <%= link_to "Borrow", books_request_path(:id => book.id), :class => "btn btn-default add-to-cart" %>
            </div>
          </div>
        </div>
        <div class="choose">
          <ul class="nav nav-pills nav-justified">
            <li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>
<!--features_items-->

app/views/books/update.html.erb
<div class='col-md-8 pad-down'>
 <form action="/save_book_data" method="post" enctype="multipart/form-data">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
  <input type="hidden" name="id" value="<%= @book.id %>" />
  <div class='form-group'>
    <label>Image: </label>
    <input class="form-control" type="file" id="image" name="image">
  </div>
  <div class='form-group'>
    <label>Title: </label>
    <input class="form-control" type="text" id="title" name="title" placeholder="eg. The Hero's Journey" value="<%= @book.title %>">
  </div>
  <div class='form-group'>
    <label>Author: </label>
    <input class="form-control" type="text" id="author" name="author" placeholder="eg. Campbell" value="<%= @book.author %>">
  </div>
  <div class='form-group'>
    <label>Blurb: </label>
    <textarea class="form-control" name="blurb" rows="5"><%= @book.blurb %></textarea>
  </div>
  <div class='form-group'>
    <label>ISBN: </label>
    <input class="form-control" type="text" id="isbn" name="isbn" value="<%= @book.isbn %>">
  </div>
  <input class="btn btn-success" id="save-book" type="submit" value="Save">
 </form>
</div>
<div class='col-md-4'>
  <img class="book-image" src="<% unless @book.image_file_name.nil? %><%= @book.image.url(:original) %><% else %>/book_not_found.png<% end %>" />
</div>